services:
  nginx_ui:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_manager
    restart: unless-stopped
    ports:
      - 80:80 # Public HTTP Port
      - 81:81 # Public HTTPS Port
      - 443:443 # Admin Web Port
    volumes:
      - /home/ubuntu/nginx_proxy_manager/data:/data
      - /home/ubuntu/letsencrypt:/etc/letsencrypt
    networks:
      - moongch-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/ubuntu/db/data:/var/lib/postgresql/data
      - /home/ubuntu/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:${DB_PORT}  # PostgreSQL 기본 포트
    networks:
      - moongch-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - 5050:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - /home/ubuntu/db/pgadmin:/var/lib/pgadmin

networks:
  moongch-network:
    driver: bridge
    external: true
