spring:
  config:
    activate:
      on-profile: dev
# 구현중
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email # openid 추가시 OIDC 플로우
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
            redirect-uri: "http://localhost:8080/login/oauth2/code/github"
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            provider: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DOMAIN}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create  # 테이블이 없을 경우 생성, 테이블이 있을 경우 변경사항을 반영
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
  file:
    name: logs/app-dev.log

jwt:
  secret: ${JWT_SECRET}
  expiration: 1h
  header: Authorization
  prefix: Bearer
  issuer: moongch.com
  type: JWT
  algorithm: HS256
  refresh:
    expiration: 24h
    header: Refresh

server:
  tomcat:
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto
