name: moongch-be-app Test

on:
  pull_request:
    branches: [ 'develop' ]
    paths-ignore:
      - '.github/**'
      - 'docs/readme.md'
    types: [ opened, synchronize ] # PR의 상태 변경 이벤트

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: ⬆️ Checkout repository
        uses: actions/checkout@v4

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: 🔑 Grant execute permission
        run: chmod +x ./gradlew  # 실행 권한 부여

      - name: 🧪 Run Tests with 'test' profile
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew test

